databases:
  - name: fynd-db
    databaseName: fynd_reviews
    user: fynd_user
    plan: free

services:
  - type: web
    name: fynd-backend
    env: python
    plan: free
    rootDir: task2_web_app
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fynd-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
